#!/usr/bin/env bash
#
# Forthway Command Center — Agent server installer for "@@SERVER_NAME@@"
#
# Generated by your panel with this server's id and token filled in. Run it as
# root on the Agent server (Ubuntu 22.04/24.04 or Debian 12):
#
#   curl -fsSL "<panel>/install/node.sh?server=…&token=…" | sudo bash
#
# It installs Node.js 20 (if needed), pm2 and nginx, downloads the agent from
# the panel into /opt/fcc-node, writes /etc/fcc-node/config.json (mode 600) and
# runs the agent as the systemd service fcc-node. The agent only makes
# outbound connections to the panel. Safe to re-run (it updates in place).
#
# Options (environment):  FCC_PHP=1  also install php-fpm for PHP websites
#                         FCC_SKIP_UFW=1  do not touch the firewall
#
set -euo pipefail

PANEL_URL="@@PANEL_URL@@"
SERVER_ID="@@SERVER_ID@@"
SERVER_TOKEN="@@SERVER_TOKEN@@"
MAIN_IPS="@@MAIN_IPS@@"
AGENT_FILES="@@AGENT_FILES@@"

INSTALL_DIR="/opt/fcc-node"
CONFIG_DIR="/etc/fcc-node"
DATA_DIR="/var/lib/fcc-node"
SITES_DIR="/srv/fcc/sites"
SITE_PORTS="3000:3999"
MIN_NODE_MAJOR=18

if [ -t 1 ]; then
  B=$'\033[1m'; DIM=$'\033[2m'; G=$'\033[32m'; Y=$'\033[33m'; R=$'\033[31m'; N=$'\033[0m'
else
  B=""; DIM=""; G=""; Y=""; R=""; N=""
fi
step() { printf '\n%s\n' "${B}> $*${N}"; }
ok()   { printf '%s\n' "  ${G}OK${N} $*"; }
warn() { printf '%s\n' "  ${Y}!${N}  $*"; }
die()  { printf '\n%s\n\n' "  ${R}x  $*${N}" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

printf '\n%s\n' "${B}Forthway Command Center — Agent server \"@@SERVER_NAME@@\"${N}"
printf '%s\n' "${DIM}  panel: ${PANEL_URL}  ·  server: ${SERVER_ID}${N}"

[ "$(id -u)" -eq 0 ] || die "Run this as root (pipe it to: sudo bash)."
have apt-get || die "This installer supports Ubuntu and Debian (apt) only."
export DEBIAN_FRONTEND=noninteractive

# ------------------------------------------------------------ packages

step "Installing system packages"
APT_UPDATED=0
apt_install() {
  if [ "$APT_UPDATED" -eq 0 ]; then apt-get update -qq >/dev/null; APT_UPDATED=1; fi
  apt-get install -y -qq "$@" >/dev/null
}
NEED=""
for p in curl ca-certificates tar gzip; do dpkg -s "$p" >/dev/null 2>&1 || NEED="$NEED $p"; done
have nginx || NEED="$NEED nginx"
[ -n "$NEED" ] && apt_install $NEED
ok "curl, tar, nginx"

if [ "${FCC_PHP:-0}" = "1" ]; then
  if ! ls /run/php/php*-fpm.sock >/dev/null 2>&1; then
    apt_install php-fpm php-mysql php-curl php-mbstring php-xml php-zip php-gd php-intl php-bcmath
  fi
  ok "php-fpm"
fi

node_major() { have node || { echo 0; return; }; node -v 2>/dev/null | sed 's/^v//' | cut -d. -f1; }
if [ "$(node_major)" -lt "$MIN_NODE_MAJOR" ]; then
  step "Installing Node.js 20"
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash - >/dev/null 2>&1 || die "Could not add the NodeSource repository."
  apt-get install -y -qq nodejs >/dev/null || die "Could not install Node.js."
fi
[ "$(node_major)" -ge "$MIN_NODE_MAJOR" ] || die "Node.js ${MIN_NODE_MAJOR}+ is required."
ok "Node.js $(node -v)"

if ! have pm2; then
  npm install -g pm2 --no-audit --no-fund >/dev/null 2>&1 || die "Could not install pm2."
fi
ok "pm2 $(pm2 -v 2>/dev/null | tail -1)"
# Restore site processes after a reboot (pm2-root.service, PM2_HOME=/root/.pm2).
export PM2_HOME=/root/.pm2
if ! systemctl is-enabled pm2-root >/dev/null 2>&1; then
  pm2 startup systemd -u root --hp /root >/dev/null 2>&1 || warn "could not set up pm2 startup — sites may not come back after a reboot"
fi
pm2 save >/dev/null 2>&1 || true

systemctl enable --now nginx >/dev/null 2>&1 || warn "nginx did not start — check: systemctl status nginx"
# The stock default site would answer on :80 for any host; this server is only reached by the panel.
[ -L /etc/nginx/sites-enabled/default ] && rm -f /etc/nginx/sites-enabled/default && (nginx -t >/dev/null 2>&1 && systemctl reload nginx || true)
ok "nginx $(nginx -v 2>&1 | sed 's/.*\///')"

# --------------------------------------------------------------- agent

step "Downloading the agent from the panel"
curl -fsS --max-time 15 "${PANEL_URL}/healthz" >/dev/null 2>&1 \
  || die "Cannot reach ${PANEL_URL} from this server. Check the panel address and any firewall in between."

mkdir -p "$INSTALL_DIR" "$CONFIG_DIR" "$DATA_DIR" "$SITES_DIR"
chmod 700 "$CONFIG_DIR" "$DATA_DIR"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
for f in $AGENT_FILES; do
  case "$f" in
    node/*.mjs|shared/*.mjs|panel/lib/sys.mjs) ;;
    *) die "Refusing unexpected file from the panel: $f" ;;
  esac
  mkdir -p "$STAGE/$(dirname "$f")"
  curl -fsS --max-time 60 -H "Authorization: Bearer ${SERVER_TOKEN}" \
    "${PANEL_URL}/install/files/${f}" -o "$STAGE/$f" || die "Could not download $f — is the token still valid?"
done
cp -R "$STAGE"/. "$INSTALL_DIR"/
node --check "$INSTALL_DIR/node/node-agent.mjs" || die "The downloaded agent does not parse."
ok "agent installed in ${INSTALL_DIR}"

umask 077
cat > "$CONFIG_DIR/config.json" <<JSON
{
  "panelUrl": "${PANEL_URL}",
  "serverId": "${SERVER_ID}",
  "token": "${SERVER_TOKEN}",
  "dataDir": "${DATA_DIR}"
}
JSON
chmod 600 "$CONFIG_DIR/config.json"
umask 022
ok "configuration written to ${CONFIG_DIR}/config.json"

NODE_BIN="$(command -v node)"
cat > /etc/systemd/system/fcc-node.service <<UNIT
[Unit]
Description=Forthway Command Center agent
After=network-online.target nginx.service
Wants=network-online.target

[Service]
Type=simple
User=root
Environment=FCC_NODE_CONFIG=${CONFIG_DIR}/config.json
Environment=PM2_HOME=/root/.pm2
Environment=NODE_ENV=production
ExecStart=${NODE_BIN} ${INSTALL_DIR}/node/node-agent.mjs
Restart=always
RestartSec=3
# Site processes belong to pm2, not to this service.
KillMode=process

[Install]
WantedBy=multi-user.target
UNIT
systemctl daemon-reload
systemctl enable fcc-node >/dev/null 2>&1
systemctl restart fcc-node
ok "running as systemd service fcc-node"

# ------------------------------------------------------------ firewall

if [ "${FCC_SKIP_UFW:-0}" != "1" ] && have ufw && ufw status 2>/dev/null | grep -q "Status: active"; then
  step "Firewall"
  if [ -z "$MAIN_IPS" ]; then
    warn "the panel did not report its IP — allow ports ${SITE_PORTS}/tcp from the main server yourself"
  else
    for ip in $MAIN_IPS; do
      ufw allow from "$ip" to any port "$SITE_PORTS" proto tcp comment "fcc sites from main" >/dev/null
      ok "site ports ${SITE_PORTS} open to ${ip} only"
    done
  fi
fi

# --------------------------------------------------------------- verify

step "Checking in with the panel"
CONNECTED=0
for _ in $(seq 1 20); do
  if journalctl -u fcc-node --since "-2min" --no-pager 2>/dev/null | grep -q "connected to"; then CONNECTED=1; break; fi
  sleep 1
done
if [ "$CONNECTED" -eq 1 ]; then
  printf '\n%s\n' "${B}  Connected.${N} This Agent server now shows as online in your panel."
else
  warn "the agent is installed but has not checked in yet — it keeps retrying on its own."
  printf '%s\n' "  watch it with:  journalctl -u fcc-node -f"
fi
printf '%s\n\n' "  ${DIM}service: systemctl status fcc-node   ·   logs: journalctl -u fcc-node -f${N}"
