#!/usr/bin/env bash
#
# Forthway agent installer — for "@@SITE_NAME@@"
#
# Generated by your Command Center with this site's id and token already in
# it. Run it on the machine that runs this site. It installs Node and pm2 if
# they are missing, drops the agent in /opt/forthway-agent, starts it under
# pm2, and checks in. Then you set the app directory and build commands from
# the dashboard — nothing else to configure here.
#
# Overrides:  FCC_AGENT_DIR=/opt/forthway-agent   FCC_AGENT_NAME=<pm2 name>
#
set -euo pipefail

HUB_URL="@@HUB_URL@@"
SITE_ID="@@SITE_ID@@"
SITE_TOKEN="@@SITE_TOKEN@@"

MIN_NODE_MAJOR=18
NAME="${FCC_AGENT_NAME:-forthway-agent-${SITE_ID}}"

if [ -t 1 ]; then
  B=$'\033[1m'; DIM=$'\033[2m'; G=$'\033[32m'; Y=$'\033[33m'; R=$'\033[31m'; N=$'\033[0m'
else
  B=""; DIM=""; G=""; Y=""; R=""; N=""
fi
say()  { printf '%s\n' "  $*"; }
step() { printf '\n%s\n' "${B}> $*${N}"; }
ok()   { printf '%s\n' "  ${G}OK${N} $*"; }
warn() { printf '%s\n' "  ${Y}!${N}  $*"; }
die()  { printf '\n%s\n\n' "  ${R}x  $*${N}" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

IS_ROOT=0; [ "$(id -u)" -eq 0 ] && IS_ROOT=1
SUDO=""; [ "$IS_ROOT" -eq 0 ] && have sudo && SUDO="sudo"
if [ "$IS_ROOT" -eq 1 ]; then DIR="${FCC_AGENT_DIR:-/opt/forthway-agent}/${SITE_ID}"
else DIR="${FCC_AGENT_DIR:-$HOME/.forthway-agent}/${SITE_ID}"; fi

printf '\n%s\n' "${B}Forthway agent — @@SITE_NAME@@${N}"
printf '%s\n' "${DIM}  hub: ${HUB_URL}  ·  site: ${SITE_ID}${N}"

have curl || die "curl is required."

# ------------------------------------------------------------------- node

node_major() { have node || { echo 0; return; }; node -v 2>/dev/null | sed 's/^v//' | cut -d. -f1; }

step "Checking prerequisites"
if [ "$(node_major)" -lt "$MIN_NODE_MAJOR" ]; then
  warn "installing Node.js"
  if have apt-get; then
    curl -fsSL https://deb.nodesource.com/setup_22.x | $SUDO bash - >/dev/null 2>&1 || true
    $SUDO env DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs >/dev/null 2>&1 || true
  elif have dnf; then
    curl -fsSL https://rpm.nodesource.com/setup_22.x | $SUDO bash - >/dev/null 2>&1 || true
    $SUDO dnf install -y nodejs >/dev/null 2>&1 || true
  elif have yum; then
    curl -fsSL https://rpm.nodesource.com/setup_22.x | $SUDO bash - >/dev/null 2>&1 || true
    $SUDO yum install -y nodejs >/dev/null 2>&1 || true
  elif have apk; then
    $SUDO apk add --no-cache nodejs npm >/dev/null 2>&1 || true
  elif have pacman; then
    $SUDO pacman -Sy --noconfirm nodejs npm >/dev/null 2>&1 || true
  fi
  [ "$(node_major)" -ge "$MIN_NODE_MAJOR" ] || die "Node ${MIN_NODE_MAJOR}+ is required. Install it and re-run this."
fi
ok "Node $(node -v)"

USE_PM2=1
if ! have pm2; then
  warn "installing pm2"
  if [ "$IS_ROOT" -eq 1 ]; then npm install -g pm2 >/dev/null 2>&1 || USE_PM2=0
  else
    npm install -g pm2 >/dev/null 2>&1 || {
      export NPM_CONFIG_PREFIX="$HOME/.npm-global"; mkdir -p "$NPM_CONFIG_PREFIX"
      export PATH="$NPM_CONFIG_PREFIX/bin:$PATH"
      npm install -g pm2 >/dev/null 2>&1 || USE_PM2=0
    }
  fi
fi
have pm2 && ok "pm2 $(pm2 -v 2>/dev/null | tail -1)" || warn "no pm2 — the agent will run in the background instead"

# --------------------------------------------------- reachability + source

step "Fetching the agent from your Command Center"
curl -fsS "${HUB_URL}/healthz" >/dev/null 2>&1 \
  || die "Cannot reach ${HUB_URL} from this machine. Check the address and anything firewalling it."

mkdir -p "$DIR/agent" "$DIR/shared"
fetch() {
  curl -fsS "${HUB_URL}/install/files/$1?site=${SITE_ID}&token=${SITE_TOKEN}" -o "$2" \
    || die "Could not download $1 — is the token still valid?"
}
fetch agent/agent.mjs      "$DIR/agent/agent.mjs"
fetch shared/deployer.mjs  "$DIR/shared/deployer.mjs"
fetch shared/zip.mjs       "$DIR/shared/zip.mjs"
fetch shared/zipwrite.mjs  "$DIR/shared/zipwrite.mjs"
fetch shared/fsx.mjs       "$DIR/shared/fsx.mjs"
ok "agent downloaded to ${DIR}"

cat > "$DIR/agent/agent.config.json" <<JSON
{
  "hubUrl": "${HUB_URL}",
  "siteId": "${SITE_ID}",
  "agentToken": "${SITE_TOKEN}",
  "workDir": ".forthway"
}
JSON
chmod 600 "$DIR/agent/agent.config.json"
ok "configuration written"

# ------------------------------------------------------------------- start

step "Starting the agent"
if [ "$USE_PM2" -eq 1 ] && have pm2; then
  pm2 delete "$NAME" >/dev/null 2>&1 || true
  ( cd "$DIR/agent" && pm2 start agent.mjs --name "$NAME" --time >/dev/null )
  pm2 save >/dev/null 2>&1 || true
  ok "running as pm2 process \"${NAME}\""
  if [ "$IS_ROOT" -eq 1 ]; then
    pm2 startup systemd -u root --hp /root >/dev/null 2>&1 && pm2 save >/dev/null 2>&1 \
      && ok "pm2 will bring it back after a reboot" || true
  fi
else
  pkill -f "$DIR/agent/agent.mjs" 2>/dev/null || true
  ( cd "$DIR/agent" && nohup node agent.mjs >"$DIR/agent.log" 2>&1 & )
  sleep 2
fi

# ------------------------------------------------------------------ verify

step "Checking in with the Command Center"
CONNECTED=0
for _ in $(seq 1 20); do
  if curl -fsS -X POST "${HUB_URL}/agent/poll" \
       -H "content-type: application/json" -H "x-fcc-token: ${SITE_TOKEN}" \
       -d "{\"siteId\":\"${SITE_ID}\"}" >/dev/null 2>&1; then
    CONNECTED=1; break
  fi
  sleep 1
done

if [ "$CONNECTED" -eq 1 ]; then
  printf '\n%s\n' "${B}  Connected.${N}"
  printf '%s\n' "  ${DIM}This site now shows as online in your Command Center. Open it and set${N}"
  printf '%s\n' "  ${DIM}the app directory, port, build commands and restart mode — then deploy.${N}"
else
  warn "the agent is installed but has not checked in yet."
  say "it keeps retrying on its own. To watch it:"
  if have pm2; then say "  pm2 logs ${NAME}"; else say "  tail -f ${DIR}/agent.log"; fi
fi
have pm2 && printf '\n%s\n' "  ${DIM}pm2:  pm2 status   ·   pm2 logs ${NAME}   ·   pm2 restart ${NAME}${N}"
printf '\n'
